import { useEffect, useState } from "react";
import { createPortal } from "react-dom";
import { Link } from "wouter";

type SectionKey = "whatsapp" | "accountability" | "useCases" | "ai" | "resources" | "faq";
export const HOMEPAGE_GROWTH_SECTIONS: SectionKey[] = ["whatsapp", "accountability", "useCases", "ai", "resources", "faq"];

const faqs = [
  ["Can I track my goals through WhatsApp?", "Yes. GotThis lets you report progress through WhatsApp and keeps your goal tracking connected to those updates, so you do not have to remember to open a separate tracker every time you make progress."],
  ["What is an AI accountability partner?", "An AI accountability partner helps keep goals visible through regular prompts, progress check-ins and next-action decisions. The useful part is not simply reminding you; it is creating a repeatable accountability loop."],
  ["How is GotThis different from a normal goal tracking app?", "Most trackers wait for you to open them. GotThis is built around conversation and check-ins, letting you update progress from WhatsApp while still giving you a dashboard when you want the bigger picture."],
  ["Can GotThis help if I miss a goal or fall behind?", "A missed day should not end the goal. Your progress history gives you context, while check-ins make it easier to acknowledge what happened and continue with the next realistic action."],
  ["What kinds of goals can I track?", "GotThis can support measurable personal goals such as study targets, writing projects, reading, routines, learning goals and activity goals. The clearest goals have an outcome or action you can report consistently."],
  ["Do I need to download another app?", "No. The core GotThis experience is designed around WhatsApp. A web dashboard is available for reviewing goals and progress in more detail."],
];

function WhatsAppSection() { return <section className="pub-section pub-features"><div className="pub-wrap"><div className="pub-section-head"><div><div className="pub-section-eyebrow">↳ WhatsApp goal tracking</div><h2 className="pub-section-title">Your goals can live where your <em>conversations</em> already happen.</h2></div><p className="pub-section-lede">GotThis turns WhatsApp into a simple input for your goals. Report what you did in normal language, keep moving, and use the dashboard when you want the full picture.</p></div><div className="pub-feat-grid"><div className="pub-feat"><h3>Set the goal.</h3><p>Start with a clear outcome: pages written, kilometres run, lessons completed, sessions finished, or another result that matters to you.</p></div><div className="pub-feat"><h3>Reply with progress.</h3><p>Instead of navigating forms, send the kind of update you would naturally text: what you finished, what changed, or what got in the way.</p></div><div className="pub-feat"><h3>See momentum build.</h3><p>Your updates become useful progress signals so you can see what is moving, what has stalled, and where your attention belongs next.</p></div></div></div></section>; }
function AccountabilitySection() { return <section className="pub-section pub-how"><div className="pub-wrap"><div className="pub-section-head"><div><div className="pub-section-eyebrow">↳ Accountability, not notification noise</div><h2 className="pub-section-title">A reminder says "do it." Accountability asks <em>what happened?</em></h2></div><p className="pub-section-lede">Reminders are easy to swipe away. An accountability loop gives you a reason to respond, record the result and decide what happens next.</p></div><div className="pub-steps"><div className="pub-step"><div className="pub-step-num">01</div><div className="pub-step-key">Prompt</div><h3 className="pub-step-title">Bring the commitment back into view.</h3><p className="pub-step-body">A timely check-in reconnects you with the goal before it quietly disappears behind everything else.</p></div><div className="pub-step"><div className="pub-step-num">02</div><div className="pub-step-key">Report</div><h3 className="pub-step-title">Say what actually happened.</h3><p className="pub-step-body">Progress, a partial win, a blocker or a miss all give you better information than an untouched checkbox.</p></div><div className="pub-step"><div className="pub-step-num">03</div><div className="pub-step-key">Continue</div><h3 className="pub-step-title">Choose the next realistic action.</h3><p className="pub-step-body">Consistency is easier when one missed day becomes feedback instead of a reason to abandon the entire goal.</p></div></div></div></section>; }
function UseCasesSection() { const cases = [["Study & learning","Finish chapters, lessons, practice sessions or study blocks."],["Projects & writing","Track milestones, pages, focused work sessions and deliverables."],["Personal routines","Keep recurring commitments visible without building another complicated system."],["Activity goals","Log measurable sessions, distance, repetitions or other progress you choose to track."]]; return <section className="pub-section pub-deep"><div className="pub-wrap"><div className="pub-section-head"><div><div className="pub-section-eyebrow">↳ Built for real goals</div><h2 className="pub-section-title">One accountability loop. <em>Different ambitions.</em></h2></div><p className="pub-section-lede">GotThis works best when you can describe what progress means and report it consistently.</p></div><div className="pub-feat-grid">{cases.map(([title,body]) => <div className="pub-feat" key={title}><h3>{title}</h3><p>{body}</p></div>)}</div></div></section>; }
function AiSection() { return <section className="pub-phrase"><div className="pub-wrap" style={{ maxWidth: 920 }}><div className="pub-section-eyebrow" style={{ marginBottom: 20 }}>↳ AI accountability partner</div><blockquote style={{ fontSize: "clamp(2rem, 4vw, 4rem)" }}>"The useful AI isn't another place to plan. It's the one that notices whether you followed through."</blockquote><p style={{ maxWidth: 720, margin: "28px auto 0", textAlign: "center", opacity: .72, lineHeight: 1.7 }}>GotThis uses AI to make natural-language progress updates useful: connecting what you report with the goals you are working toward and supporting a more conversational accountability experience.</p><div style={{ textAlign: "center", marginTop: 24 }}><Link href="/questions/what-is-an-ai-accountability-partner" className="pub-btn pub-btn-ghost">What is an AI accountability partner? →</Link></div></div></section>; }
function ResourcesSection() { const resources = [["Question","How do I stay accountable to my goals?","/questions/how-to-stay-accountable-to-your-goals"],["Question","Can I track my goals through WhatsApp?","/questions/can-i-track-goals-through-whatsapp"],["Guide","How to track your goals without making it complicated","/guides/how-to-track-your-goals"]]; return <section className="pub-section pub-features"><div className="pub-wrap"><div className="pub-section-head"><div><div className="pub-section-eyebrow">↳ Goal & accountability resources</div><h2 className="pub-section-title">Learn the system behind <em>following through.</em></h2></div><p className="pub-section-lede">Practical answers and guides for building a goal-tracking process you can actually keep using.</p></div><div className="pub-feat-grid">{resources.map(([type,title,href]) => <Link href={href} className="pub-feat" key={href} style={{ textDecoration: "none", color: "inherit" }}><div className="pub-section-eyebrow">↳ {type}</div><h3>{title}</h3><p>Read the answer →</p></Link>)}</div><div style={{ marginTop: 28, display: "flex", gap: 12, flexWrap: "wrap" }}><Link href="/questions" className="pub-btn pub-btn-ghost">Browse questions</Link><Link href="/guides" className="pub-btn pub-btn-ghost">Browse guides</Link></div></div></section>; }
function FaqSection() { return <section className="pub-section pub-how"><div className="pub-wrap"><div className="pub-section-head"><div><div className="pub-section-eyebrow">↳ Common questions</div><h2 className="pub-section-title">Goals, WhatsApp and <em>accountability.</em></h2></div><p className="pub-section-lede">Straight answers to the questions people ask before changing how they track their goals.</p></div><div style={{ display: "grid", borderTop: "1px solid rgba(127,127,127,.2)" }}>{faqs.map(([q,a]) => <details key={q} style={{ borderBottom: "1px solid rgba(127,127,127,.2)", padding: "22px 0" }}><summary style={{ cursor: "pointer", fontWeight: 600, fontSize: "1.08rem" }}>{q}</summary><p style={{ maxWidth: 800, marginTop: 14, lineHeight: 1.75, opacity: .72 }}>{a}</p></details>)}</div></div></section>; }
const components: Record<SectionKey, () => JSX.Element> = { whatsapp: WhatsAppSection, accountability: AccountabilitySection, useCases: UseCasesSection, ai: AiSection, resources: ResourcesSection, faq: FaqSection };
function Sections({ sections }: { sections: SectionKey[] }) { return <>{sections.map((key) => { const Section = components[key]; return <Section key={key} />; })}</>; }

// Mount immediately before the existing CTA band. This keeps landing.tsx visually untouched and
// makes the extension removable/reorderable as a single experiment surface.
export default function HomepageGrowthSections({ sections = HOMEPAGE_GROWTH_SECTIONS }: { sections?: SectionKey[] }) {
  const [mount, setMount] = useState<HTMLElement | null>(null);
  useEffect(() => {
    const cta = document.querySelector<HTMLElement>(".pub-cta-band");
    if (!cta?.parentElement) return;
    const host = document.createElement("div");
    host.dataset.homepageGrowth = "true";
    cta.parentElement.insertBefore(host, cta);
    setMount(host);
    return () => host.remove();
  }, []);
  return mount ? createPortal(<Sections sections={sections} />, mount) : null;
}
