import { useEffect, useState } from "react";
import { createPortal } from "react-dom";
import { Link } from "wouter";
type SectionKey = "whatsapp" | "accountability" | "useCases" | "ai" | "resources" | "faq";
export const HOMEPAGE_GROWTH_SECTIONS: SectionKey[] = ["whatsapp", "accountability", "useCases", "ai", "resources", "faq"];
const faqs = [
["Can I track my goals through WhatsApp?","Yes. Set a goal and send GotThis a message when you make progress. For example: “I read 10 pages today.”"],
["What is an AI accountability partner?","It is an AI that checks in about your goals. You tell it what you did. It helps you keep your goals in sight."],
["How is GotThis different from a normal goal app?","Many goal apps wait for you to open them. GotThis lets you send progress updates through WhatsApp. You can open the dashboard when you want to see more."],
["What if I miss a day?","Start again. One missed day does not end your goal. Tell GotThis what happened and keep going."],
["What kinds of goals can I track?","You can track goals like reading, studying, writing, learning and personal projects. For example: read 10 pages a day or study for 30 minutes."],
["Do I need to download another app?","No. You can use GotThis through WhatsApp. You can also use the web dashboard to see your goals and progress."]];
function WhatsAppSection(){return <section className="pub-section pub-features"><div className="pub-wrap"><div className="pub-section-head"><div><div className="pub-section-eyebrow">↳ WhatsApp goal tracking</div><h2 className="pub-section-title">Track your goals with a simple <em>message.</em></h2></div><p className="pub-section-lede">Do the work. Send GotThis a message. See your progress. It is that simple.</p></div><div className="pub-feat-grid"><div className="pub-feat"><h3>Pick a goal.</h3><p>Make it clear. For example: “Read 100 pages this month.”</p></div><div className="pub-feat"><h3>Send an update.</h3><p>Tell GotThis what you did. For example: “I read 20 pages today.”</p></div><div className="pub-feat"><h3>See your progress.</h3><p>Open your dashboard when you want to see how close you are to your goal.</p></div></div></div></section>}
function AccountabilitySection(){return <section className="pub-section pub-how"><div className="pub-wrap"><div className="pub-section-head"><div><div className="pub-section-eyebrow">↳ Stay on track</div><h2 className="pub-section-title">A reminder says “do it.” A check-in asks <em>“did you?”</em></h2></div><p className="pub-section-lede">GotThis can ask about your goal. You answer with what you did. Then you keep going.</p></div><div className="pub-steps"><div className="pub-step"><div className="pub-step-num">01</div><div className="pub-step-key">Check in</div><h3 className="pub-step-title">Remember your goal.</h3><p className="pub-step-body">GotThis brings your goal back to you so it is harder to forget.</p></div><div className="pub-step"><div className="pub-step-num">02</div><div className="pub-step-key">Reply</div><h3 className="pub-step-title">Say what you did.</h3><p className="pub-step-body">Done, partly done, or not done. A simple answer is enough.</p></div><div className="pub-step"><div className="pub-step-num">03</div><div className="pub-step-key">Keep going</div><h3 className="pub-step-title">Take the next step.</h3><p className="pub-step-body">Missed a day? That is okay. Start again and keep moving.</p></div></div></div></section>}
function UseCasesSection(){const cases=[["Reading","Try: “Read 10 pages every day.”"],["Studying","Try: “Study for 30 minutes after school.”"],["Writing","Try: “Write 500 words each day.”"],["Projects","Try: “Finish three lessons this week.”"]];return <section className="pub-section pub-deep"><div className="pub-wrap"><div className="pub-section-head"><div><div className="pub-section-eyebrow">↳ Goals you can track</div><h2 className="pub-section-title">Big goal or small goal. <em>Start simple.</em></h2></div><p className="pub-section-lede">Pick something you can do, count, or finish.</p></div><div className="pub-feat-grid">{cases.map(([t,b])=><div className="pub-feat" key={t}><h3>{t}</h3><p>{b}</p></div>)}</div></div></section>}
function AiSection(){return <section className="pub-phrase"><div className="pub-wrap" style={{maxWidth:920}}><div className="pub-section-eyebrow" style={{marginBottom:20}}>↳ AI accountability partner</div><blockquote style={{fontSize:"clamp(2rem, 4vw, 4rem)"}}>“GotThis checks in. You tell it what you did. Then you keep going.”</blockquote><p style={{maxWidth:720,margin:"28px auto 0",textAlign:"center",opacity:.72,lineHeight:1.7}}>You can write like you normally do. Say, “I walked for 20 minutes.” GotThis can use your message to help track your goal.</p><div style={{textAlign:"center",marginTop:24}}><Link href="/questions/what-is-an-ai-accountability-partner" className="pub-btn pub-btn-ghost">Learn about AI accountability →</Link></div></div></section>}
function ResourcesSection(){const r=[["Question","How do I stay accountable to my goals?","/questions/how-to-stay-accountable-to-your-goals"],["Question","Can I track my goals through WhatsApp?","/questions/can-i-track-goals-through-whatsapp"],["Guide","How to track your goals","/guides/how-to-track-your-goals"],["Free tool","Check your goal progress","/tools/goal-progress-calculator"]];return <section className="pub-section pub-features"><div className="pub-wrap"><div className="pub-section-head"><div><div className="pub-section-eyebrow">↳ Simple guides</div><h2 className="pub-section-title">Want help with your <em>goals?</em></h2></div><p className="pub-section-lede">Read simple answers and guides. Or use a free tool.</p></div><div className="pub-feat-grid">{r.map(([type,title,href])=><Link href={href} className="pub-feat" key={href} style={{textDecoration:"none",color:"inherit"}}><div className="pub-section-eyebrow">↳ {type}</div><h3>{title}</h3><p>Open →</p></Link>)}</div></div></section>}
function FaqSection(){return <section className="pub-section pub-how"><div className="pub-wrap"><div className="pub-section-head"><div><div className="pub-section-eyebrow">↳ Common questions</div><h2 className="pub-section-title">Quick questions. <em>Simple answers.</em></h2></div><p className="pub-section-lede">Here are a few things people may want to know.</p></div><div style={{display:"grid",borderTop:"1px solid rgba(127,127,127,.2)"}}>{faqs.map(([q,a])=><details key={q} style={{borderBottom:"1px solid rgba(127,127,127,.2)",padding:"22px 0"}}><summary style={{cursor:"pointer",fontWeight:600,fontSize:"1.08rem"}}>{q}</summary><p style={{maxWidth:800,marginTop:14,lineHeight:1.75,opacity:.72}}>{a}</p></details>)}</div></div></section>}
const components:Record<SectionKey,()=>JSX.Element>={whatsapp:WhatsAppSection,accountability:AccountabilitySection,useCases:UseCasesSection,ai:AiSection,resources:ResourcesSection,faq:FaqSection};
function Sections({sections}:{sections:SectionKey[]}){return <>{sections.map(key=>{const Section=components[key];return <Section key={key}/>})}</>}
export default function HomepageGrowthSections({sections=HOMEPAGE_GROWTH_SECTIONS}:{sections?:SectionKey[]}){const[mount,setMount]=useState<HTMLElement|null>(null);useEffect(()=>{const cta=document.querySelector<HTMLElement>(".pub-cta-band");if(!cta?.parentElement)return;const host=document.createElement("div");host.dataset.homepageGrowth="true";cta.parentElement.insertBefore(host,cta);setMount(host);return()=>host.remove()},[]);return mount?createPortal(<Sections sections={sections}/>,mount):null}